# Stage 09 — Homework Starter Notebook

In the lecture, we learned how to create engineered features. Now it’s your turn to apply those ideas to your own project data.

In [7]:
import pandas as pd
import numpy as np
from pathlib import Path
#project data
data_path = Path('../data/raw/fraud_kaggle_creditcard_source-kaggle_dataset-creditcardfraud_20250820-192958.csv')
df = pd.read_csv(data_path)
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

## TODO: Implement at least 2 engineered features here

### Problem with adding features due to PCA
The dataset used has already undergone PCA so there are 28 anonymized features other than amount and time, which aren't directly related. Therfore adding features that aren't time based is difficult, as the featues have already been engineered.

In [ ]:
#use datetime to group by hour and minute
df['datetime'] = pd.to_datetime(df['Time'], unit='s')
df = df.sort_values('Time').reset_index(drop=True)

# Transactions per hour (group by hour)
df['hour_group'] = df['datetime'].dt.floor('h')
transactions_per_hour = df.groupby('hour_group').size().reset_index(name='hourly_transactions')
df = df.merge(transactions_per_hour, on='hour_group', how='left')

df['minute_group'] = df['datetime'].dt.floor('min')
transactions_per_minute = df.groupby('minute_group').size().reset_index(name='minute_transactions')
df = df.merge(transactions_per_minute, on='minute_group', how='left')

df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V26,V27,V28,Amount,Class,datetime,hour_group,hourly_transactions,minute_group,minute_transactions
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.189115,0.133558,-0.021053,149.62,0,1970-01-01 00:00:00,1970-01-01 00:00:00,3963,1970-01-01 00:00:00,91
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,0.125895,-0.008983,0.014724,2.69,0,1970-01-01 00:00:00,1970-01-01 00:00:00,3963,1970-01-01 00:00:00,91
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,-0.139097,-0.055353,-0.059752,378.66,0,1970-01-01 00:00:01,1970-01-01 00:00:00,3963,1970-01-01 00:00:00,91
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.221929,0.062723,0.061458,123.50,0,1970-01-01 00:00:01,1970-01-01 00:00:00,3963,1970-01-01 00:00:00,91
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,0.502292,0.219422,0.215153,69.99,0,1970-01-01 00:00:02,1970-01-01 00:00:00,3963,1970-01-01 00:00:00,91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.250034,0.943651,0.823731,0.77,0,1970-01-02 23:59:46,1970-01-02 23:00:00,4856,1970-01-02 23:59:00,58
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,-0.395255,0.068472,-0.053527,24.79,0,1970-01-02 23:59:47,1970-01-02 23:00:00,4856,1970-01-02 23:59:00,58
284804,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.546668,0.108821,0.104533,10.00,0,1970-01-02 23:59:48,1970-01-02 23:00:00,4856,1970-01-02 23:59:00,58
284805,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,-0.087371,0.004455,-0.026561,67.88,0,1970-01-02 23:59:48,1970-01-02 23:00:00,4856,1970-01-02 23:59:00,58
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,-0.818267,-0.002415,0.013649,217.00,0,1970-01-02 23:59:52,1970-01-02 23:00:00,4856,1970-01-02 23:59:00,58

# Feature explanation
##V1 - V28 are all anonymized engineered or original features that can be helpful during training; first columns used are based on maggnitude in coefficient matrix
##The other transactions, specifically _transactions are the number of transactions in that timestep, which can be used